services:
  - type: web
    name: pyexpo-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -b 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: PUBLIC_URL
        value: "" # Will be populated by Render's domain if not using ngrok bypass
